version: '3'
services:
  app:
    build: .
    container_name: vuejs_app
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
